name: CI

on:
  push:
    branches: ["development", "main"]
  pull_request:
    types: [opened, synchronize]
    branches:
      - development
      - main

jobs:
  build:
    name: Build Packages
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Create app env
        run: cp .env.example .env
        working-directory: ./app

      - name: Set app adapter to node
        run: echo 'ADAPTER = node' >> .env
        working-directory: ./app

      - name: Build all packages
        run: npm run build

      - name: Upload the app build output
        uses: actions/upload-artifact@v2
        with:
          name: build-output
          path: |
            app/build
          retention-days: 1

  testApp:
    name: Test App
    needs: [build]
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Download the build output
        uses: actions/download-artifact@v2
        with:
          name: build-output

      - name: Start SvelteKit Server
        run: node build &
        working-directory: ./app

      - name: Run cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          project: ./app
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Stop SvelteKit Server
        run: pkill -f "sirv" || true

  testHTMLGenerator:
    name: Test HTML Generator
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: publish-html
        run: cd doc/reference-course; npm i -g tutors-gen-lib; npx -y ts-node ../../cli/tutors-publish-html/src/tutors-publish-html.ts
      - name: Run cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          record: true
          project: ./doc/reference-course
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.HTML_CYPRESS_RECORD_KEY }}
