name: CI

on:
  push:
    branches: ["development", "main"]
  pull_request:
    types: [opened, synchronize]
    branches:
      - development
      - main

jobs:
  app:
    name: Build & Test App
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Create app env
        run: cp .env.example .env
        working-directory: ./app

      - name: Build app
        run: npm run build
        working-directory: ./app

      - name: Run preview & cypress tests
        run: npm run preview & npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }} --browser chrome
        working-directory: ./app

  publish-html:
    name: Build & test tutors-publish-html
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install Dependencies
        run: npm install
        working-directory: ./cli/tutors-publish-html
      - name: Build tutors-publish-html
        run: npm run build
        working-directory: ./cli/tutors-publish-html
      - name: Run tutors-publish-html on example course
        run: node ../../cli/tutors-publish-html/src/tutors-publish-html.js
        working-directory: ./doc/reference-course
      - name: Run cypress tests
        run: npx cypress run --record --key ${{ secrets.HTML_CYPRESS_RECORD_KEY }} --browser chrome
        working-directory: ./doc/reference-course

  publish:
    name: Build tutors-publish
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: Install Dependencies
        run: npm install
        working-directory: ./cli/tutors-publish
      - name: Build tutors-publish
        run: npm run build
        working-directory: ./cli/tutors-publish
