name: CI

on:
  push:
    branches: ["development", "main"]
  pull_request:
    types: [opened, synchronize]
    branches:
      - development
      - main

jobs:
  build:
    name: Build & Test App
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install dependencies
        run: npm install
        working-directory: ./app

      - name: Buils, Serve & run cypress tests
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          record: true
          build: npm run build
          start: npm run preview
          wait-on: "http://localhost:3000"
          command: npm run test
          project: ./app
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

  testHTMLGenerator:
    name: Test HTML Generator
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm install
      - name: publish-html
        run: cd doc/reference-course; npm i -g tutors-gen-lib; npx -y ts-node ../../cli/tutors-publish-html/src/tutors-publish-html.ts
      - name: Run cypress tests
        uses: cypress-io/github-action@v5
        with:
          browser: chrome
          record: true
          project: ./doc/reference-course
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.HTML_CYPRESS_RECORD_KEY }}
